### ISSUE TITLE
Evidence Page arrows don't show up for Private Evidence

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#887] opened 2023-01-23 22:58 UTC
**Describe the bug**
when you create more evidence than shown in private evidence, arrows don't show up to move between pages. I dunno when this broke cuz it worked at one point.

**To reproduce**
create enough evidence in private evidence/transfer evidence from global to see the issue

**Expected behavior**
evidence page arrows appear

**Screenshots**
![image](https://user-images.githubusercontent.com/3470436/214171242-3d544e76-337e-4822-8847-2d6f50bc6575.png)

**Version:**
 - OS:  Windows 10
 - Version or branch:  2.10

**Comment by Salanto** [comment] 2023-01-30 00:21
Seems to be dependent on which theme you use.

**Comment by in1tiate** [comment] 2023-02-03 08:57
the entire evidence system needs tearing out and replacing and has done for years

via [evidence.py](https://github.com/AttorneyOnline/tsuserver3/blob/master/server/evidence.py) lines 202-205 on [AttorneyOnline/tsuserver3](https://github.com/AttorneyOnline/tsuserver3):
```
            # Are you serious? This is absolutely fucking mental.
            # Server sends evidence to client in an indexed list starting from 1.
            # Client sends evidence updates to server using an index starting from 0.
            # This needs a complete overhaul.
```
which according to git blame, was written by @Crystalwarrior in 2020.

**Comment by in1tiate** [comment] 2023-02-04 13:52
turned out to be a widget placement issue with some default themes lol. closing as not a bug

**Closed by in1tiate** 2023-02-04 13:52 UTC
Labels: bug
