### ISSUE TITLE
Making your text too fast locks up IC chat.

### ISSUE THREAD

**Issue by collinxchu** [AttorneyOnline/AO2-Client#243] opened 2020-08-14 16:58 UTC
If you type text in ic chat with four } it locks the text chat similarly to https://github.com/AttorneyOnline/AO2-Client/issues/226 .  Potentially the same issue.

**Comment by likeawindrammer** [comment] 2020-08-14 17:42
Fixed in 2.8.5 ask LB to release it

**Comment by likeawindrammer** [comment] 2020-08-14 18:41
Duplicate of https://github.com/AttorneyOnline/AO2-Client/issues/231 and fixed with https://github.com/AttorneyOnline/AO2-Client/pull/232
Closing.

**Closed by likeawindrammer** 2020-08-14 18:41 UTC
