### ISSUE TITLE
Rare pairing crash

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#44] opened 2018-12-16 02:22 UTC
The root cause is undetermined, since I have only been able to produce this crash once.

Sometimes, when clicking on a character in the pair menu, the character will fail to be selected (the "[x]" is not shown) and the client will shortly crash thereafter.

A stack trace is almost mandatory to investigate this issue, but a crash condition certainly does exist somewhere.

**Comment by Cerapter** [comment] 2018-12-22 09:40
I am becoming more and more certain that this is due to the "[x]" system in some way.

Not using a drop down menu for pairing was an awful lapse in judgement from my part.

**Comment by likeawindrammer** [comment] 2019-07-26 00:26
A good friend of mine that goes under the nickname Henyckma sometimes has an issue with AO 2.6.0 on Windows 10.
Today he manage to reproduce it again and I was able to see it through a discord screen share, we still haven't been able to figure the root cause. But we where both witness of a crash when he attempted to use the pair feature.

The issue happens to him **very** rarely and is something like this:
He will open AO like always and connect to the same server. He then first notice this issue on the loading screen. Where it's loading the music if for example the server has 10 songs, the loading screen will display "20/10", and the same will happen with the characters. As if it was loading every song and every character twice. Then when the char selection comes in, if he goes to what it would normally be the last page, he will see that the list of character repeats again after the last character. When he first told me about this he said that if he choose any of the duplicated chars his client would crash. But today for some reason the tried to choose the duplicated chars his client didn't crash, I believe this might be because of the patch that removes all the null chars on the server. Since this is one of the very few changes the owner has made in months (and the only change to the code since the server has months without updating an only that patch was applied). This time, instead of having his client crash, he just couldn't select any of the duplicated characters. After selecting one of the non-duplicated characters he could join the server almost like normally. Except the song list would repeat after the last song, very much like the character selection did. The areas list would also repeat in the same way. But the repeated areas would show "Unknown | Unknown" instead of "[idle] | CM: FREE".

The relationship with the pairing issue:
After we confirmed that selecting any of the duplicated chars, songs and areas didn't crash his client like it did before the null char path thing was applied to the server. I told him to try to pair with another user. So he opened the pair menu, searched for the character we would pair with and selected it. Just seconds after this his client crashed. Only his client did crash though. Nobody else's client crashed at that time in that area or any other are in that server. He isn't completely sure if the "[x]" did or didn't show before the crash, but he says he believes it didn't show "[x]" at all.

Might be related to the null char bug:
I think this might be related to the null char bug on the client. Because even though the server was patched to remove all null chars from input (and only input), and it was only after that the patch was applied to the server that suddenly this issue with duplicated chars wouldn't crash his client, his client wasn't patched to handle null chars correctly. Another possible relationship is that even though I have never experienced duplicated character, music or areas. Or the pairing issue. I did experience the client showing "Unknown | Unknown" instead of "[idle] | CM: FREE" on every area, on a client that wasn't patched to handle null chars correctly, and this was while I was testing the null char bug. My client never crash during these tests, but assuming the null char bug could result in a crash on windows, could be platform differences since I tested the null char bug on Ubuntu 18.04

Sorry for the long ass comment, just wanted to make sure to document every detail before I forget since nobody knows the root cause of this yet, or even how to trigger it.

**Comment by oldmud0** [comment] 2019-07-26 02:51
I don't think this has anything to do with the null character bug. None of the packets in transit ever contain a null character. I think it has to do more with the way the client cleans up (or rather, fails to clean up) after it leaves a server. It is not consistently cleaning up the music and character lists - there are not one, but multiple arrays that track the state of these.

**Comment by Crystalwarrior** [comment] 2020-06-19 19:05
No clue if this is still present in 2.8

**Comment by oldmud0** [comment] 2020-06-20 03:52
No duh. This is one of those freak crash bugs that I will never be able to catch in debugging mode.

**Comment by Crystalwarrior** [comment] 2020-07-27 16:47
rip... Closing until there's a documented occurrence of this in 2.8

**Closed by Crystalwarrior** 2020-07-27 16:47 UTC
Labels: crash or hang, ui
