### ISSUE TITLE
QComboBox's border-radius selectively works with drop boxes. 

### ISSUE THREAD

**Issue by Jouto44** [AttorneyOnline/AO2-Client#758] opened 2022-04-20 01:37 UTC
Applying border-radius QComboBox doesn't work with all dropdowns. 

Accessing any theme's courtroom.css and applying border-radius of any px to QComboBox will replicate this bug.

Evidence: 
https://media.discordapp.net/attachments/470584614885261322/966111646781165668/unknown.png
https://media.discordapp.net/attachments/470584614885261322/966117084251717682/unknown.png

This issue was found on Windows 11.

**Edit**: Delving into further details on the bug.

Issue was found on Client version 2.9.1.

CSS for both themes are given in the screenshots of the original comment.

CSS for the theme in development I'm making:
https://cdn.discordapp.com/attachments/734063698964119662/966333305437962310/theme1courtroom_stylesheets.css

CSS for KFOqHD, a theme that comes with AO:
https://cdn.discordapp.com/attachments/734063698964119662/966333305744150579/kfoqHDcourtroom_stylesheets.css

**Comment by in1tiate** [comment] 2022-05-04 02:26
Confirmed still present on `master` with Windows 10

**Comment by oldmud0** [comment] 2022-06-16 03:11
1. When you change any border style on `QComboBox::drop-down` it will cause the whole dropdown arrow box to disappear. This is a known Qt "quirk".
2. The issue is prevalent in those QComboBox instances that are marked as editable. I don't know why this is happening on Windows

Either way these issues are related to Qt and don't seem to be related to AO code.

**Closed by oldmud0** 2022-06-16 03:11 UTC
Labels: bug, ui
