### ISSUE TITLE
can't select position when the background is missing

### ISSUE THREAD

**Issue by stonedDiscord** [AttorneyOnline/AO2-Client#325] opened 2020-10-17 14:14 UTC
the dropdown is empty

![grafik](https://user-images.githubusercontent.com/10584181/96339255-d2ee4680-1093-11eb-838a-d2af2787e81d.png)

**Comment by oldmud0** [comment] 2020-10-18 23:47
The position dropdown is based on which positions are locally available. If the background is not available, then you're right, you can't choose a position and instead will (in theory) be assigned a position automatically by the server.

**Comment by in1tiate** [comment] 2021-01-11 04:20
Closing as this is not a bug.

**Closed by in1tiate** 2021-01-11 04:20 UTC
Labels: bug
