### ISSUE TITLE
[Bug 2.8] Checking "Pre" on an emote with modifier 5 (zoom) causes infinite IC hang until interrupted by a shout

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#226] opened 2020-08-02 05:33 UTC
Via Door#0513:

> So it's been a long ass time since i've done ini editing, so I can't tell you why this is happening. But for some reason, some of the zooms, the ones that have the .ini written "Zoom#-#/zoom#5#", if you pre up a zoom, the message won't display, and someone else has to do a shout to interupt it. Characters that are written "Zoom#-#/zoom#6#" are able to use a pre on their zoom just fine. Idk if this is intentional or not. But seeing as everyone's ini is like that, if they haven't edited it. Felt like it was worth a mention

Confirmed via my own testing to occur on multiple servers.

**Comment by collinxchu** [comment] 2020-08-12 20:15
Looks to be a 2.8 tsuserver thing, as this behavior does not occur on older servers.

**Comment by scatterflower** [comment] 2020-08-16 16:22
duplicate of #169

**Closed by scatterflower** 2020-08-16 16:22 UTC
Labels: bug, engine/timing
