### ISSUE TITLE
Evidence can escape to file structure

### ISSUE THREAD

**Issue by collinxchu** [AttorneyOnline/AO2-Client#285] opened 2020-09-07 06:17 UTC
Sanitize your inputs ree.
To replicate: Put something like ../characters/Maya/(a)mayanormal.apng as the evidence path in this box right here: [Link](https://i.imgur.com/r07j4H7.png)

Solution: Don't let it escape the above the evidence directory by scrubbing out ../ instances.

**Comment by Iamgoofball** [comment] 2020-09-07 06:33
I vote """feature"""

**Comment by collinxchu** [comment] 2020-09-07 06:37
Sanitize your inputs fat.

**Comment by raidensnake** [comment] 2020-09-07 07:32
Duplicate of https://github.com/AttorneyOnline/AO2-Client/issues/284 Please close.

**Comment by collinxchu** [comment] 2020-09-07 07:39
Not a duplicate. This has to do with evidence, not effects. Unless it's the same section of code that dictates both?

**Comment by in1tiate** [comment] 2020-09-07 07:53
Yeah, it's the section of code in your operating system that dictates ".." means "go up a directory." This is the same underlying issue, closing as duplicate of #284.

**Closed by in1tiate** 2020-09-07 07:53 UTC
